### PR TITLE
add 'auto' style option,

### PR DESCRIPTION
**Pull request by josefbehr**
don't really like this solution, better would be to move to tailwind and accept custom additional tailwind classes, will maybe look into this in the future

### CODE REVIEW

**Comment by jszobody** [comment]
Yeah... I hear ya. Does Filament use Tailwind's `dark:` prefix for handling dark mode? Wonder if that's worth implementing here somehow.

**Comment by josefbehr** [comment]
Filament currently adds classes with the dark prefix, if dark mode is enabled, and adds a 'dark' class to the body tag as well, since some styles depend on that. For v3 there will be the possibility to add multiple themes though, which is also achievable using tailwind plugins now. So the most flexible way to use and customize this would probably be to add default styles for the 'dark' prefix and allow adding custom classes as well.

**Comment by jszobody** [comment]
@josefbehr What do you think of this update (not tested yet)?

- Moved all the hex colors to the config file, at least now folks can publish the config and edit if desired.
- Built out a lot more CSS vars, so we can reduce the PHP conditionals around light/dark options
- Converted the button bg color from hex to RGB (using [this approach](https://stackoverflow.com/a/15202130/660694)) so I can just use transparency levels for the button hover, instead of dealing with yet another color.

While I too would love to be using tailwind here, keep in mind that the banner is getting implemented in non-tailwind apps. This isn't just for Filament. I think it's better to stick with raw hex colors.

**Comment by josefbehr** [comment]
@jszobody Thanks. Way better now.
Regarding tailwind, that would still be a great addition. Especially since filament v3 will introduce themes and contexts, where colors might differ completely and using the defined tailwind colors such as primary, secondary, gray and so on would really help to integrate the banner with whatever design is chosen. On the other hand, I get your point of this package being used in other contexts. Maybe it would be good to separate it into two packages, one for filament (it IS called filament-impersonate still ;)) and a general one, but that would also mean more maintenance.

**Pull request merged**
