### PR TITLE
Update action name behavior

### PR DESCRIPTION
**Pull request by lloricode**
Use action getDefaultName() to be able to use in test properly.

```php
    livewire(ListAdmins::class)
        ->callTableAction(Impersonate::class, $admin);
```

### CODE REVIEW

**Comment by jszobody** [comment]
thanks!

**Comment by lloricode** [comment]
hi @jszobody, thanks for merging, can we get this with released tag?

**Comment by jszobody** [comment]
@lloricode 2.9 is tagged

**Comment by lloricode** [comment]
> @lloricode 2.9 is tagged

thank you

**Pull request merged**
