### PR TITLE
fix gap on Filament Sidebar

### PR DESCRIPTION
**Pull request by Lupennat**
fix gap on Filament Sidebar

### CODE REVIEW

**Comment by jszobody** [comment]
Thanks for this!

One problem: this banner component is being used in non-Filament apps as well as Filament. I have apps where Filament is for admins only, and clicking impersonate takes me to a Jetstream customer-facing UI, where I have added the banner component to my main layout file.

So we can't change the CSS in ways that breaks this banner in those scenarios. Modifying the `html` is how this works globally for non-Filament apps.

I wonder if we just need to break out the banner component and have one dedicated for Filament, and one for everything else. It's either that, or this CSS change needs to fix Filament while still leaving the `html` margin for everything else.

**Comment by Lupennat** [comment]
OK I understand the problem you highlight.

I made a change to make the css rule active only when included via filament hook, this way the original behavior is preserved.

**Comment by Lupennat** [comment]
any feedback about last changes?

**Comment by gexcube** [comment]
+1

**Comment by danielreales7** [comment]
Merge?

**Comment by jszobody** [comment]
Closing this in favor of #61, which has now been merged.

**Pull request closed without merging**
